version: '3.8'

services:
  system-monitor:
    build: .
    container_name: system-monitor
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    environment:
      - LOG_LEVEL=INFO
